# -*- coding: utf-8 -*-
"""클라우드플랫폼(포스터).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZfdJb2GGUt8wDnOsiO8UjCmSfgJVBOaJ
"""

pip install MTCNN

from mtcnn.mtcnn import MTCNN
import matplotlib.pyplot as plt
import pandas as pd
import glob
import os

image = plt.imread('/content/drive/MyDrive/클라우드  플랫폼 /데이터/포스터 데이터/포스터/포스터/train575.jpg')
detector = MTCNN()
results = detector.detect_faces(image)
results

def draw_facebox(filename, result_list):
    data = plt.imread(filename)
    plt.imshow(data)
    ax = plt.gca()
    for result in result_list:
        x, y, width, height = result['box']
        rect = plt.Rectangle((x, y), width, height, fill=False, color='pink')
        ax.add_patch(rect)
    plt.show()

draw_facebox('/content/drive/MyDrive/클라우드  플랫폼 /데이터/포스터 데이터/포스터/포스터/train575.jpg', results)

# 얼굴 수 세기

counts = []
counts.append(len(results))

counts = pd.DataFrame(counts)
counts.columns = ['counts']
counts

file_list = sorted(os.listdir('/content/drive/MyDrive/클라우드  플랫폼 /데이터/포스터 데이터/포스터/포스터/'), key=len)
file_name = []
for file in file_list:
  if file.count(".") == 1:
    name = file.split('.')[0]
    file_name.append(name)
  else:
    for k in range(len(file)-1,0,-1):
      if file[k]=='.':
        file_name.append(file[:k])
        break
file_name

file_name = pd.DataFrame(file_name)
file_name.columns = ['인덱스']
file_name

# 포스터 파일 안에 있는 이미지 파일 한꺼번에 처리

output = []

for filename in glob.glob('/content/drive/MyDrive/클라우드  플랫폼 /데이터/포스터 데이터/포스터/포스터/*.jpg'):
  image = plt.imread(filename)
  detector = MTCNN()
  results = detector.detect_faces(image)
  results

  output.append(len(results))

# 포스터 파일 안에 있는 얼굴 수 데이터프레임으로 반환

import numpy as np

output = np.array(output)
output = pd.DataFrame(output)
output.columns = ['counts']
output